[Interface]
PrivateKey = aFY8K29OrnPnJCgoxEg8bGY5GlzTCQD206im4nyUsnE=
Address = 100.69.217.74/32
DNS = 10.255.255.3

[Peer]
PublicKey = 5LYbbr320XMoXPrLsZex+2cDAMUOnzX5Htpcgb4Uc1c=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = ord-323-wg.whiskergalaxy.com:65142
PresharedKey = jKhWUPLuGDOh0rwYGwCcR8gnP87XNIOH5rrAb4PdikU=
